// Centralized Settings Types for MyDresser

export interface ThemeSettings {
  mode: 'light' | 'dark' | 'system';
  primaryColor: string;
  accentColor: string;
  fontSize: 'small' | 'medium' | 'large';
  fontFamily: string;
  highContrast: boolean;
}

export interface PrivacySettings {
  profilePublic: boolean;
  showWardrobeSize: boolean;
  showFollowerCount: boolean;
  showFollowingCount: boolean;
  showStyleScore: boolean;
  allowMessages: 'everyone' | 'following' | 'none';
  showActivity: boolean;
  dataSharing: boolean;
  analyticsOptIn: boolean;
}

export interface NotificationSettings {
  emailNotifications: boolean;
  pushNotifications: boolean;
  
  // Outfit notifications
  outfitSuggestions: boolean;
  dailyOutfitTime: string; // "09:00"
  
  // Market notifications
  marketUpdates: boolean;
  priceDropAlerts: boolean;
  newListings: boolean;
  offerReceived: boolean;
  
  // Social notifications
  socialActivity: boolean;
  newFollower: boolean;
  postComment: boolean;
  postLike: boolean;
  mention: boolean;
  
  // System notifications
  systemUpdates: boolean;
  securityAlerts: boolean;
}

export interface WardrobeSettings {
  // Display preferences
  defaultView: 'grid' | 'list' | 'compact';
  itemsPerPage: number;
  showWearCount: boolean;
  showPriceInfo: boolean;
  showCostPerWear: boolean;
  
  // Organization
  defaultSort: 'recent' | 'category' | 'color' | 'season' | 'favorite';
  enableAutoCategorization: boolean;
  enableSmartSuggestions: boolean;
  
  // Maintenance
  laundryReminders: boolean;
  maintenanceAlerts: boolean;
  cleaningSchedule: boolean;
  
  // Privacy
  allowSocialSharing: boolean;
  showInMarketplace: boolean;
}

export interface OutfitSettings {
  // AI & Weather
  weatherIntegration: boolean;
  autoGenerateDaily: boolean;
  dailyGenerationTime: string; // "09:00"
  
  // Preferences
  occasionPreferences: string[];
  avoidRecentItems: boolean;
  daysToAvoidReuse: number;
  includeAccessories: boolean;
  minimalStyle: boolean;
  
  // Matching
  strictColorMatching: boolean;
  allowMixedStyles: boolean;
  preferFavorites: boolean;
}

export interface SocialSettings {
  // Profile visibility
  profilePublic: boolean;
  showFollowerCount: boolean;
  showFollowingCount: boolean;
  showStyleScore: boolean;
  
  // Content sharing
  autoShareOutfits: boolean;
  allowComments: boolean;
  allowReactions: boolean;
  shareToFeed: boolean;
  
  // Privacy
  blockedUsers: string[];
  mutedUsers: string[];
  allowMessages: 'everyone' | 'following' | 'none';
  
  // Notifications (social-specific)
  notifyOnFollow: boolean;
  notifyOnComment: boolean;
  notifyOnLike: boolean;
  notifyOnMention: boolean;
}

export interface MarketplaceSettings {
  // Display
  defaultCurrency: string;
  showLocalOnly: boolean;
  maxShippingDistance: number;
  
  // Transactions
  enablePurchases: boolean;
  savedPaymentMethods: string[];
  defaultShippingAddress?: Address;
  
  // Selling
  enableSelling: boolean;
  defaultShippingOptions: ShippingOption[];
  autoAcceptOffers: boolean;
  autoDeclineThreshold: number; // percentage
  
  // Notifications
  notifyOnPriceDrops: boolean;
  notifyOnNewListings: boolean;
  notifyOnOffers: boolean;
  notifyOnSales: boolean;
}

export interface MyMirrorSettings {
  // Camera
  preferredCamera: 'front' | 'back';
  photoQuality: 'low' | 'medium' | 'high';
  autoCapture: boolean;
  
  // Virtual Try-On
  enableARTryOn: boolean;
  showSizeRecommendations: boolean;
  saveTryOnHistory: boolean;
  
  // Privacy
  autoDeletePhotos: boolean;
  photosRetentionDays: number;
}

export interface SustainabilitySettings {
  trackCarbonFootprint: boolean;
  showSustainabilityScore: boolean;
  preferEcoFriendly: boolean;
  highlightSecondHand: boolean;
  circulaeconomyPreference: boolean;
}

export interface ChallengeSettings {
  participateInDaily: boolean;
  participateInWeekly: boolean;
  participateInCommunity: boolean;
  notifyOnNewChallenges: boolean;
  showOnLeaderboard: boolean;
  autoAcceptChallenges: boolean;
}

export interface AISettings {
  // Model preferences
  preferredModel: 'google/gemini-2.5-flash' | 'google/gemini-2.5-pro' | 'openai/gpt-5-mini';
  
  // Feature toggles
  enableStyleChat: boolean;
  enableOutfitSuggestions: boolean;
  enableVirtualTryOn: boolean;
  enableWardrobeInsights: boolean;
  enableTrendAnalysis: boolean;
  
  // Personalization
  stylePreferences: Record<string, any>;
  colorPreferences: string[];
  brandPreferences: string[];
  
  // Privacy
  allowAIDataCollection: boolean;
  shareAnonymousData: boolean;
  
  // Limits
  dailyRequestLimit: number;
  enableUsageAlerts: boolean;
}

export interface MerchantSettings {
  // Store Info
  storeName: string;
  storeDescription: string;
  
  // Operations
  businessHours: BusinessHours;
  taxRate: number;
  currency: string;
  autoAcceptOrders: boolean;
  orderProcessingTime: number; // hours
  
  // Inventory
  enableStockAlerts: boolean;
  lowStockThreshold: number;
  autoReorder: boolean;
  
  // Customer Management
  enableCustomerReviews: boolean;
  requireReviewModeration: boolean;
  enableLoyaltyProgram: boolean;
  
  // Marketing
  enablePromotions: boolean;
  enableEmailMarketing: boolean;
  
  // Analytics
  enableAnalytics: boolean;
  enableOrderTracking: boolean;
  
  // Payment
  paymentGateway: string;
  acceptedPaymentMethods: string[];
  enableInstallments: boolean;
  commissionRate: number;
  
  // Appearance
  storeTheme: string;
  brandColors: {
    primary: string;
    secondary: string;
  };
  customCSS?: string;
}

export interface AccessibilitySettings {
  screenReader: boolean;
  keyboardNavigation: boolean;
  highContrast: boolean;
  reducedMotion: boolean;
  fontSize: 'small' | 'medium' | 'large' | 'extra-large';
  colorBlindMode?: 'none' | 'deuteranopia' | 'protanopia' | 'tritanopia';
}

// Main settings interface combining all feature settings
export interface AppSettings {
  // Core settings
  theme: ThemeSettings;
  privacy: PrivacySettings;
  notifications: NotificationSettings;
  accessibility: AccessibilitySettings;
  
  // Feature settings
  wardrobe: WardrobeSettings;
  outfit: OutfitSettings;
  social: SocialSettings;
  marketplace: MarketplaceSettings;
  myMirror: MyMirrorSettings;
  sustainability: SustainabilitySettings;
  challenges: ChallengeSettings;
  ai: AISettings;
  
  // Merchant settings (only for merchant accounts)
  merchant?: MerchantSettings;
  
  // Metadata
  lastUpdated: string;
  version: string;
}

// Supporting types
export interface Address {
  street: string;
  city: string;
  state: string;
  zipCode: string;
  country: string;
}

export interface ShippingOption {
  id: string;
  name: string;
  cost: number;
  estimatedDays: number;
  carrier?: string;
}

export interface BusinessHours {
  monday: { open: string; close: string; closed?: boolean };
  tuesday: { open: string; close: string; closed?: boolean };
  wednesday: { open: string; close: string; closed?: boolean };
  thursday: { open: string; close: string; closed?: boolean };
  friday: { open: string; close: string; closed?: boolean };
  saturday: { open: string; close: string; closed?: boolean };
  sunday: { open: string; close: string; closed?: boolean };
}

// Default settings
export const DEFAULT_THEME_SETTINGS: ThemeSettings = {
  mode: 'system',
  primaryColor: '#000000',
  accentColor: '#ff6b35',
  fontSize: 'medium',
  fontFamily: 'Inter',
  highContrast: false,
};

export const DEFAULT_PRIVACY_SETTINGS: PrivacySettings = {
  profilePublic: false,
  showWardrobeSize: true,
  showFollowerCount: true,
  showFollowingCount: true,
  showStyleScore: true,
  allowMessages: 'following',
  showActivity: false,
  dataSharing: false,
  analyticsOptIn: true,
};

export const DEFAULT_NOTIFICATION_SETTINGS: NotificationSettings = {
  emailNotifications: true,
  pushNotifications: true,
  outfitSuggestions: true,
  dailyOutfitTime: '09:00',
  marketUpdates: true,
  priceDropAlerts: true,
  newListings: false,
  offerReceived: true,
  socialActivity: true,
  newFollower: true,
  postComment: true,
  postLike: true,
  mention: true,
  systemUpdates: true,
  securityAlerts: true,
};

export const DEFAULT_WARDROBE_SETTINGS: WardrobeSettings = {
  defaultView: 'grid',
  itemsPerPage: 20,
  showWearCount: true,
  showPriceInfo: true,
  showCostPerWear: true,
  defaultSort: 'recent',
  enableAutoCategorization: true,
  enableSmartSuggestions: true,
  laundryReminders: true,
  maintenanceAlerts: true,
  cleaningSchedule: false,
  allowSocialSharing: true,
  showInMarketplace: false,
};

export const DEFAULT_OUTFIT_SETTINGS: OutfitSettings = {
  weatherIntegration: true,
  autoGenerateDaily: true,
  dailyGenerationTime: '09:00',
  occasionPreferences: ['casual', 'business'],
  avoidRecentItems: true,
  daysToAvoidReuse: 3,
  includeAccessories: true,
  minimalStyle: false,
  strictColorMatching: false,
  allowMixedStyles: true,
  preferFavorites: false,
};

export const DEFAULT_AI_SETTINGS: AISettings = {
  preferredModel: 'google/gemini-2.5-flash',
  enableStyleChat: true,
  enableOutfitSuggestions: true,
  enableVirtualTryOn: false,
  enableWardrobeInsights: true,
  enableTrendAnalysis: true,
  stylePreferences: {},
  colorPreferences: [],
  brandPreferences: [],
  allowAIDataCollection: true,
  shareAnonymousData: false,
  dailyRequestLimit: 100,
  enableUsageAlerts: true,
};

// Helper function to get default settings
export const getDefaultSettings = (): Partial<AppSettings> => ({
  theme: DEFAULT_THEME_SETTINGS,
  privacy: DEFAULT_PRIVACY_SETTINGS,
  notifications: DEFAULT_NOTIFICATION_SETTINGS,
  wardrobe: DEFAULT_WARDROBE_SETTINGS,
  outfit: DEFAULT_OUTFIT_SETTINGS,
  ai: DEFAULT_AI_SETTINGS,
  lastUpdated: new Date().toISOString(),
  version: '1.0.0',
});
