import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Input } from '@/components/ui/input';
import { useSettings } from '@/hooks/useSettings';
import type { OutfitSettings } from '@/types/settings';
import { Separator } from '@/components/ui/separator';

export const OutfitSettingsPanel = () => {
  const { outfit, updateFeatureSettings, saving } = useSettings();

  const handleUpdate = (updates: Partial<OutfitSettings>) => {
    updateFeatureSettings('outfit', updates);
  };

  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-sm font-medium mb-4">AI & Weather Integration</h3>
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <Label htmlFor="weather-integration">Weather Integration</Label>
            <Switch
              id="weather-integration"
              checked={outfit?.weatherIntegration ?? true}
              onCheckedChange={(checked) => handleUpdate({ weatherIntegration: checked })}
              disabled={saving}
            />
          </div>

          <div className="flex items-center justify-between">
            <Label htmlFor="auto-generate">Auto Generate Daily Outfit</Label>
            <Switch
              id="auto-generate"
              checked={outfit?.autoGenerateDaily ?? true}
              onCheckedChange={(checked) => handleUpdate({ autoGenerateDaily: checked })}
              disabled={saving}
            />
          </div>

          {outfit?.autoGenerateDaily && (
            <div>
              <Label htmlFor="generation-time">Daily Generation Time</Label>
              <Input
                id="generation-time"
                type="time"
                value={outfit?.dailyGenerationTime || '09:00'}
                onChange={(e) => handleUpdate({ dailyGenerationTime: e.target.value })}
                disabled={saving}
              />
            </div>
          )}
        </div>
      </div>

      <Separator />

      <div>
        <h3 className="text-sm font-medium mb-4">Preferences</h3>
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <Label htmlFor="avoid-recent">Avoid Recent Items</Label>
            <Switch
              id="avoid-recent"
              checked={outfit?.avoidRecentItems ?? true}
              onCheckedChange={(checked) => handleUpdate({ avoidRecentItems: checked })}
              disabled={saving}
            />
          </div>

          {outfit?.avoidRecentItems && (
            <div>
              <Label htmlFor="days-to-avoid">Days to Avoid Reuse</Label>
              <Input
                id="days-to-avoid"
                type="number"
                min="1"
                max="14"
                value={outfit?.daysToAvoidReuse || 3}
                onChange={(e) => handleUpdate({ daysToAvoidReuse: parseInt(e.target.value) })}
                disabled={saving}
              />
            </div>
          )}

          <div className="flex items-center justify-between">
            <Label htmlFor="include-accessories">Include Accessories</Label>
            <Switch
              id="include-accessories"
              checked={outfit?.includeAccessories ?? true}
              onCheckedChange={(checked) => handleUpdate({ includeAccessories: checked })}
              disabled={saving}
            />
          </div>

          <div className="flex items-center justify-between">
            <Label htmlFor="minimal-style">Minimal Style</Label>
            <Switch
              id="minimal-style"
              checked={outfit?.minimalStyle || false}
              onCheckedChange={(checked) => handleUpdate({ minimalStyle: checked })}
              disabled={saving}
            />
          </div>
        </div>
      </div>

      <Separator />

      <div>
        <h3 className="text-sm font-medium mb-4">Matching Rules</h3>
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <Label htmlFor="strict-color">Strict Color Matching</Label>
            <Switch
              id="strict-color"
              checked={outfit?.strictColorMatching || false}
              onCheckedChange={(checked) => handleUpdate({ strictColorMatching: checked })}
              disabled={saving}
            />
          </div>

          <div className="flex items-center justify-between">
            <Label htmlFor="mixed-styles">Allow Mixed Styles</Label>
            <Switch
              id="mixed-styles"
              checked={outfit?.allowMixedStyles ?? true}
              onCheckedChange={(checked) => handleUpdate({ allowMixedStyles: checked })}
              disabled={saving}
            />
          </div>

          <div className="flex items-center justify-between">
            <Label htmlFor="prefer-favorites">Prefer Favorites</Label>
            <Switch
              id="prefer-favorites"
              checked={outfit?.preferFavorites || false}
              onCheckedChange={(checked) => handleUpdate({ preferFavorites: checked })}
              disabled={saving}
            />
          </div>
        </div>
      </div>
    </div>
  );
};
